description: The Dart analyzer settings with stricter linter rules that allow you to write more maintainable code and improve performance.
version: 0.3.0
homepage: https://github.com/xalabax/static_analyzer

environment:
  sdk: ">=2.12.0-0 <4.0.0"

name: static_analyze_av

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
